name: flash_message
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.4.3
  cloud_firestore: ^4.15.5
  # firebase_core_platform_interface: ^5.0.0
  modal_progress_hud_nsn: ^0.5.1
  firebase_messaging: ^14.7.17
  get_storage: ^2.1.1
  get: ^4.6.6
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  push: ^2.1.0
  flutter_local_notifications: ^10.0.0
  http: ^0.13.3
  system_alert_window: ^2.0.0
  share_plus: ^7.2.2
  # flutter_overlay_window: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: in.jvapps.system_alert_window
        pluginClass: SystemAlertWindowPlugin

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #
